### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by mahajanmayur97** [AnamKhurshid17/ReactFrontEnd#1]
how to run this project

**Comment by AnamKhurshid17** [comment]
Download and extract the project in VS Code. Write run commands on command prompt. The project will run on browser automatically.

**Comment by mahajanmayur97** [comment]
C:\Users\Omkar infotech\Desktop\BusReservation\ReactFrontEnd>npm start

> my-app@0.1.0 start C:\Users\Omkar
infotech\Desktop\BusReservation\ReactFrontEnd
> react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Omkar
infotech\Desktop\BusReservation\ReactFrontEnd\node_modules\react-scripts\bin\react-scripts.js'
    at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain]
(internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Omkar
infotech\AppData\Roaming\npm-cache\_logs\2021-03-02T15_46_10_675Z-debug.log

**Comment by mahajanmayur97** [comment]
Hi Sir,
   I'm mayur. I am doing a online bus reservation project using react as
frontEnd & nodejs express as backEnd.
I really like your project. but unable to run it.
If possible Plzz guide me....
